version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myapplication
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  spring_app:
    image: sakit333/spring_app:latest
    container_name: spring-app
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: Spring_sak
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myapplication?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SERVER_PORT: 8081
      SPRING_SERVLET_MULTIPART_ENABLED: true
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 5MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 5MB
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:

