version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - my-network

  sakgroup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springapp
    image: sakgroup  
    ports:
      - "8081:8081"
    networks:
      - my-network

networks:
  my-network:  
    name: my-network
    driver: bridge
