name: Deploy Spring Boot App with MySQL using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Spring Boot app JAR file
      - name: Build Spring Boot app JAR
        run: mvn clean package -DskipTests

      # Step 5: Build Docker image for Spring Boot app
      - name: Build Docker image for Spring Boot app
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sakgroup:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/sakgroup:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/sakgroup:latest

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sakgroup:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/sakgroup:latest

      # Step 7: Deploy using Docker Compose (Optional - if you're running the containers on a remote server)
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
