name: Docker Deployment

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build spring jar file
      run: mvn clean package -DskipTests

    - name: Build and push Docker image
      run: |
        # Build the Docker image
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sakgroup:latest .
      
        # Show a message that the Docker image has been prepared
        echo "Docker image sakgroup:latest has been successfully built."
      
        # Optionally, push the image to Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/sakgroup:latest
      
        # Confirm image is available
        echo "Docker image sakgroup:latest has been successfully pushed to Docker Hub."
